services:
  
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: frontend_image
    ports: 
      - 9000:9000
    depends_on:
      - backend   
  
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: backend_image
    ports: 
      - 5252:5252
 