services:
  
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: frontend_image
    depends_on:
      - backend   
  
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: backend_image
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy_image
    ports: 
      - 80:80
    depends_on:
      - backend
      - frontend
  
  
 